# Generated by Django 5.1.5 on 2025-02-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
                ('dateAjout', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=255)),
                ('prenomClient', models.CharField(max_length=255)),
                ('adresseClient', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFacture', models.CharField(max_length=50)),
                ('prixTotal', models.FloatField(default=0.0)),
                ('dateFacture', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreProduit', models.IntegerField(default=0)),
                ('prixTotal', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('en cours', 'En Cours'), ('validé', 'Validé')], default='en cours')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.client')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(max_length=255)),
                ('imageProduit', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('quantite', models.IntegerField(default=0)),
                ('prixUnitaire', models.FloatField(default=0.0)),
                ('dateAjout', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixAchat', models.FloatField(default=0.0)),
                ('dateAchat', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.facture')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.panier')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.produit')),
            ],
        ),
    ]
