# Generated by Django 5.1.5 on 2025-02-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='imageProduit',
            field=models.ImageField(upload_to='produits/'),
        ),
    ]
