# Generated by Django 5.1.5 on 2025-02-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0003_categorie_imagecategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(default='description categorie'),
        ),
    ]
