# Generated by Django 5.1.5 on 2025-02-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0004_categorie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom_categorie',
            new_name='nomCategorie',
        ),
    ]
