# Generated by Django 5.1.5 on 2025-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0005_rename_nom_categorie_categorie_nomcategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='nbreProduit',
            field=models.IntegerField(default=0),
        ),
    ]
