# Generated by Django 5.1.5 on 2025-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0006_categorie_nbreproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='dateAjout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
