# Generated by Django 5.1.5 on 2025-02-08 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0007_alter_categorie_dateajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achat',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SmartShop.facture'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.produit'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numeroFacture',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='panier',
            name='statut',
            field=models.CharField(choices=[('en cours', 'En Cours'), ('validé', 'Validé')], default='en cours', max_length=10),
        ),
    ]
