# Generated by Django 5.1.5 on 2025-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0008_achat_quantite_alter_achat_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(default='00000000', max_length=20),
        ),
    ]
