# Generated by Django 5.1.5 on 2025-02-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0010_alter_client_adresseclient_alter_client_nomclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='SmartShop.client'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SmartShop.client'),
        ),
    ]
