# Generated by Django 5.1.5 on 2025-02-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0011_alter_panier_client_alter_vente_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.client'),
        ),
    ]
