# Generated by Django 5.1.5 on 2025-02-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0012_alter_panier_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
        migrations.AddField(
            model_name='vente',
            name='adresse',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vente',
            name='dateVente',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='nomClient',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vente',
            name='prenomClient',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vente',
            name='prixtTotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vente',
            name='telephone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
