# Generated by Django 5.1.5 on 2025-02-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0014_facture_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SmartShop.panier'),
        ),
    ]
