# Generated by Django 5.1.5 on 2025-02-25 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0015_alter_achat_panier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vente',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='panier',
            field=models.OneToOneField(default=87, on_delete=django.db.models.deletion.PROTECT, to='SmartShop.panier'),
        ),
        migrations.AddField(
            model_name='panier',
            name='date_creation',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
