# Generated by Django 5.1.5 on 2025-02-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0016_delete_vente_remove_achat_facture_facture_panier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='panier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='SmartShop.panier'),
        ),
    ]
