# Generated by Django 5.1.5 on 2025-02-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0017_alter_client_telephone_alter_facture_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
    ]
