# Generated by Django 5.1.5 on 2025-02-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0018_alter_panier_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panier',
            name='date_creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
