# Generated by Django 5.1.5 on 2025-02-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0019_alter_panier_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='panier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.panier'),
        ),
    ]
