# Generated by Django 5.1.5 on 2025-02-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartShop', '0020_alter_facture_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartShop.panier'),
        ),
    ]
